# Generated by Django 5.1.3 on 2025-02-24 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_atual', models.IntegerField()),
                ('quant_litros', models.FloatField()),
                ('valor', models.FloatField()),
                ('img_abastecimento', models.ImageField(upload_to='imagens/abastecimento')),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('data_alteracao', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Forma_Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.CharField(default='Indefinido', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_atual', models.IntegerField()),
                ('data_prevista', models.DateField()),
                ('valor_manutencao', models.FloatField()),
                ('comentario', models.TextField()),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('data_alteracao', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prioridade_Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prioridade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateField()),
                ('data_entrega', models.DateField()),
                ('idade_condutor', models.IntegerField()),
                ('valor', models.FloatField()),
                ('forma_pagamento', models.CharField(max_length=30)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('data_alteracao', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('cidade_inicio', models.CharField(max_length=100)),
                ('cidade_fim', models.CharField(max_length=100)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('data_alteracao', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status_Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_status', models.CharField(max_length=100)),
                ('status_cor', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status_Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Indefinido', max_length=50)),
                ('status_cor', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Carga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr_carga', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Combustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_combustivel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_manutencao', models.CharField(max_length=100)),
            ],
        ),
    ]
