# Generated by Django 5.1.4 on 2025-01-27 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Forma_Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.CharField(default='Indefinido', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Status_Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Indefinido', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status_Uso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status_Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Indefinido', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StatusUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuário',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=15)),
                ('senha', models.CharField(max_length=128)),
                ('data_cadastro', models.DateField(auto_now=True)),
                ('rua', models.CharField(max_length=35)),
                ('bairro', models.CharField(max_length=35)),
                ('cidade', models.CharField(max_length=35)),
                ('cep', models.CharField(max_length=15)),
                ('imagem', models.ImageField(default='carro-escondido.jpg', upload_to='imagens/usuario')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.estado')),
                ('status_usuario', models.ForeignKey(default='indefinido', on_delete=django.db.models.deletion.SET_DEFAULT, to='dashboard.statususuario')),
                ('tipo_usuario', models.ForeignKey(default='indefinido', on_delete=django.db.models.deletion.SET_DEFAULT, to='dashboard.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=100)),
                ('valor_compra', models.CharField(max_length=25)),
                ('ano', models.IntegerField()),
                ('km', models.CharField(max_length=20)),
                ('motor', models.CharField(max_length=10)),
                ('placa', models.CharField(max_length=20)),
                ('chassi', models.CharField(max_length=20)),
                ('cor', models.CharField(default='indefinido', max_length=50)),
                ('imagem', models.ImageField(default='media/carro-escondido.jpg', upload_to='imagens/veiculos')),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('data_alteracao', models.DateField(auto_now=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos_status', to='dashboard.status_veiculo')),
                ('usuario_alteracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculos_alterados', to='dashboard.usuário')),
                ('usuario_cadastro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculos_cadastrados', to='dashboard.usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateField()),
                ('data_entrega', models.DateField()),
                ('idade_condutor', models.IntegerField()),
                ('valor', models.FloatField()),
                ('forma_pagamento', models.CharField(max_length=30)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('data_alteracao', models.DateField(auto_now=True)),
                ('status_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_status', to='dashboard.status_reserva')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_como_motorista', to='dashboard.usuário')),
                ('usuario_alteracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_alteradas', to='dashboard.usuário')),
                ('usuario_cadastro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_cadastradas', to='dashboard.usuário')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='dashboard.veiculo')),
            ],
        ),
    ]
