# Generated by Django 5.1.3 on 2025-01-21 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status_Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Indefinido', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=100)),
                ('valor_compra', models.CharField(max_length=25)),
                ('ano', models.IntegerField()),
                ('km', models.CharField(max_length=20)),
                ('motor', models.CharField(max_length=10)),
                ('placa', models.CharField(max_length=20)),
                ('chassi', models.CharField(max_length=20)),
                ('cor', models.CharField(default='indefinido', max_length=50)),
                ('imagem', models.ImageField(default='media/carro-escondido.jpg', upload_to='imagens/veiculos')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.status_veiculo')),
            ],
        ),
    ]
