# Generated by Django 5.1.4 on 2025-02-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status_veiculo',
            name='status_cor',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
