# Generated by Django 5.1.3 on 2025-01-21 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='cor',
            field=models.CharField(default='indefinido', max_length=50),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='imagem',
            field=models.ImageField(default='media/carro-escondido.jpg', upload_to='imagens/veeiculos'),
        ),
    ]
