# Generated by Django 5.1.3 on 2024-12-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuário',
            name='imagem',
            field=models.ImageField(default='static/img/img_perfil.jpg', upload_to='images/'),
        ),
    ]
