# Generated by Django 5.1.3 on 2025-02-24 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('veiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='abastecimento',
            name='motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_abastecimento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='usuario_alteracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abastecimentos_alteradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='usuario_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abastecimentos_cadastradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculo_abastecido', to='veiculos.veiculo'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='usuario_alteracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencao_alterada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='usuario_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencao_cadastrada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='veiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculo_manutencao', to='veiculos.veiculo'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='prioridade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencao_prioridade', to='dashboard.prioridade_atendimento'),
        ),
        migrations.AddField(
            model_name='reservas',
            name='motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_como_motorista', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservas',
            name='usuario_alteracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_alteradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservas',
            name='usuario_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_cadastradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservas',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='veiculos.veiculo'),
        ),
        migrations.AddField(
            model_name='rota',
            name='reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.reservas'),
        ),
        migrations.AddField(
            model_name='rota',
            name='usuario_alteracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rota_alterada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rota',
            name='usuario_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rota_cadastrada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencao_status', to='dashboard.status_manutencao'),
        ),
        migrations.AddField(
            model_name='reservas',
            name='status_reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_status', to='dashboard.status_reserva'),
        ),
        migrations.AddField(
            model_name='rota',
            name='tipo_carga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.tipo_carga'),
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='tipo_combustivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combustivel_abastecimento', to='dashboard.tipo_combustivel'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='tipo_manutencao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencao_tipo', to='dashboard.tipo_manutencao'),
        ),
    ]
