# Generated by Django 5.1.3 on 2025-02-18 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_status_veiculo_status_cor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prioridade_Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prioridade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Combustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_combustivel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_manutencao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_atual', models.IntegerField()),
                ('quant_litros', models.FloatField()),
                ('valor', models.FloatField()),
                ('img_abastecimento', models.ImageField(upload_to='imagens/abastecimento')),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('data_alteracao', models.DateField(auto_now=True)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_abastecimento', to=settings.AUTH_USER_MODEL)),
                ('usuario_alteracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abastecimentos_alteradas', to=settings.AUTH_USER_MODEL)),
                ('usuario_cadastro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abastecimentos_cadastradas', to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculo_abastecido', to='dashboard.veiculo')),
                ('tipo_combustivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combustivel_abastecimento', to='dashboard.tipo_combustivel')),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_atual', models.IntegerField()),
                ('data_prevista', models.DateField()),
                ('valor_manutencao', models.FloatField()),
                ('comentario', models.TextField()),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('data_alteracao', models.DateField(auto_now=True)),
                ('usuario_alteracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencao_alterada', to=settings.AUTH_USER_MODEL)),
                ('usuario_cadastro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencao_cadastrada', to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculo_manutencao', to='dashboard.veiculo')),
                ('prioridade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencao_prioridade', to='dashboard.prioridade_atendimento')),
                ('tipo_manutencao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencao_tipo', to='dashboard.tipo_manutencao')),
            ],
        ),
    ]
