# Generated by Django 5.1.3 on 2025-01-21 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_estado_statususuario_tipousuario_usuário'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forma_Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.CharField(default='Indefinido', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Status_Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Indefinido', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateField()),
                ('data_entrega', models.DateField()),
                ('idade_condutor', models.IntegerField()),
                ('valor', models.FloatField()),
                ('forma_pagamento', models.CharField(max_length=30)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('data_alteracao', models.DateField(auto_now=True)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.usuário')),
                ('usuario_alteracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculos_alterados', to='dashboard.usuário')),
                ('usuario_cadastro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculos_cadastrados', to='dashboard.usuário')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.veiculo')),
                ('status_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.status_reserva')),
            ],
        ),
    ]
