# Generated by Django 5.1.3 on 2024-12-25 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_usuário_imagem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuário',
            new_name='Usuario',
        ),
    ]
