# Generated by Django 5.1.3 on 2025-02-20 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_prioridade_atendimento_tipo_combustivel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='manutencao',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencao_status', to='dashboard.status_manutencao'),
        ),
    ]
