# Generated by Django 5.1.3 on 2025-02-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_status_manutencao_manutencao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status_manutencao',
            name='status_cor',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
