# Generated by Django 5.1.3 on 2025-02-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_veiculo_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='valor_compra',
            field=models.FloatField(),
        ),
    ]
