# Generated by Django 5.1.3 on 2025-02-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_veiculo_valor_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='status_reserva',
            name='status_cor',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
