# Generated by Django 5.1.3 on 2025-02-23 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_status_reserva_status_cor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Carga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr_carga', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('cidade_inicio', models.CharField(max_length=100)),
                ('cidade_fim', models.CharField(max_length=100)),
                ('motorista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.reservas')),
                ('veiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.veiculo')),
                ('tipo_carga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.tipo_carga')),
            ],
        ),
    ]
