# Generated by Django 5.1.3 on 2025-02-23 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_tipo_carga_rota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rota',
            name='motorista',
        ),
        migrations.RemoveField(
            model_name='rota',
            name='veiculo',
        ),
    ]
