# Generated by Django 5.1.3 on 2025-02-23 04:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_rota_motorista_remove_rota_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='data_alteracao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rota',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rota',
            name='usuario_alteracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rota_alterada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rota',
            name='usuario_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rota_cadastrada', to=settings.AUTH_USER_MODEL),
        ),
    ]
