# Generated by Django 5.1.3 on 2025-02-23 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_rota_data_alteracao_rota_data_cadastro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='veiculo',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.tipo_veiculo'),
        ),
    ]
